# Generated by Django 5.0.3 on 2024-05-12 09:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cartId',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
